### PR TITLE
Vitineth/events

### PR DESCRIPTION
**Pull request by Lan2u**
Is it worth merging this aswell?

### CODE REVIEW

**Comment by Vitineth** [comment]
I'm okay with merging it but keep the branch I think. This should bring master up to a working version although many features are half implemented

**Comment by Lan2u** [comment]
> Should hopefully work as expected when run in docker because it uses the hostnames that are provided as part of the `uems-dev` network

this is what I was having problems with, in my docker setup it seems to need to use localhost:15300/ rather than gateway:15300/ - not sure if this is just me though?

**Comment by Vitineth** [comment]
Should work with `uems-gateway:15300` as in the configuration because it has to be the name of the docker container when launched

**Comment by Lan2u** [comment]
> Should work with `uems-gateway:15300` as in the configuration because it has to be the name of the docker container when launched

Yeah this is the problem at least currently when I do docker-compose it doesn't - this might be something to do with a local problem in my setup as I've had this issue with the other parts of the system as-well.

**Comment by Vitineth** [comment]
I can double check mine at some point to make sure because I might be running mine differently but to make it work just change the command in the dockerfile to `build` rather than `build:docker` and it'll use localhost when it builds instead. I'll do some debugging when I'm next on my laptop and find out

**Comment by Lan2u** [comment]
> I can double check mine at some point to make sure because I might be running mine differently but to make it work just change the command in the dockerfile to `build` rather than `build:docker` and it'll use localhost when it builds instead. I'll do some debugging when I'm next on my laptop and find out

I've just modified the config on my local build for now and I'll work it out once I know if its just my setup or a general problem (I can try it on my laptop aswell and see what happens there).

**Pull request merged**
