### PR TITLE
(vitineth/events) adding event page with provisional API loading

### PR DESCRIPTION
**Pull request by Vitineth**
This is currently waiting on API implementations but loads from the provisional API endpoints. When the API is up and working I will work more on validating the returned data and making it all nice and safe but opening this draft PR until that point. Work will probably continue from this branch because of the extent of changes including notification systems and such.

### CODE REVIEW

**Comment by Lan2u** [comment]
Unless I'm mistaken this overwrites the update to use the different API endpoints in #14? 

If so then that is good with me, we can close #14 and just wait on this.

**Comment by Vitineth** [comment]
I didn't see any new requests to api endpoints in #14 other than mapping the result from the server in Events.tsx. Keep it open for now because I'll go in and fiddle on that one but we may want to convert it to a draft for the time being until we're ready

**Comment by Lan2u** [comment]
> I didn't see any new requests to api endpoints in #14 other than mapping the result from the server in Events.tsx. Keep it open for now because I'll go in and fiddle on that one but we may want to convert it to a draft for the time being until we're ready

The names of the response fields changed when the new backend schema was introduced.

**Comment by Vitineth** [comment]
> > I didn't see any new requests to api endpoints in #14 other than mapping the result from the server in Events.tsx. Keep it open for now because I'll go in and fiddle on that one but we may want to convert it to a draft for the time being until we're ready
> 
> The names of the response fields changed when the new backend schema was introduced.

Will double check everything against the backend stuff in a little bit and make sure it's all accurate

**Comment by Lan2u** [comment]
> > > I didn't see any new requests to api endpoints in #14 other than mapping the result from the server in Events.tsx. Keep it open for now because I'll go in and fiddle on that one but we may want to convert it to a draft for the time being until we're ready
> > 
> > 
> > The names of the response fields changed when the new backend schema was introduced.
> 
> Will double check everything against the backend stuff in a little bit and make sure it's all accurate

The gateway OpenApiSpec branch will make everything API compliant either way.

**Pull request merged**
