### PR TITLE
(vitineth/event_page) Adding event page and future components

### PR DESCRIPTION
**Pull request by Vitineth**

### CODE REVIEW

**Comment by Lan2u** [comment]
I think we should merge this + your other branch as the current master is too early stage for anyone to contribute without overlapping work already done on the events/ branch

**Comment by Vitineth** [comment]
Fair enough, I'll convert it to a normal PR now. I think the problem that I was meaning to solve is actually solved in the other branch so that's all good

**Comment by Lan2u** [comment]
> Fair enough, I'll convert it to a normal PR now. I think the problem that I was meaning to solve is actually solved in the other branch so that's all good

Also I tried out your code and (at least for me) when running in docker I had to modify the config to use localhost:15300/ rather than gateway:15300/ is this a local issue to me?

**Comment by Vitineth** [comment]
Nah that was a mistake that is fixed here https://github.com/ents-crew/uems-frontend-themis/commit/237884e0cc5e9e0a4f7bb0055a5d9beeedda13a8 did it on the other branch for some reason

**Pull request merged**
