### PR TITLE
(vitineth/api-update-with-bugfixes) Adding a new API and fixing a few bugs

### PR DESCRIPTION
**Pull request by Vitineth**
The API script is now auto generated based on the open api spec. The API object should follow the exact structure of the API which will hopefully make things easier. Data from the server is now validated using Zod which also provides the inferred typescript typings. APIGen file is messy and needs cleaned up but need to figure a way to automate it.

### CODE REVIEW

**Comment by Vitineth** [comment]
This branch builds off the testing branch in #17 so some changes are duplicated

**Comment by Lan2u** [comment]
How come the CI is failing?

**Comment by Vitineth** [comment]
> How come the CI is failing?

Need to do some testing but it seems like the axios mocking isn't working properly because it needs API responses to load the pages. I either need to find a way to mock the entire API output (which is my next step) or to make the axios mocking work.

**Comment by Vitineth** [comment]
> > This branch builds off the testing branch in #17 so some changes are duplicated
> 
> Change the PR to be vs #17 so that we can see the changes this branch brings specifically

Done

**Comment by Vitineth** [comment]
@Lan2u CI passes (was an Axios mocking issue) and base changed. Quite surprised it worked that nicely and that coveralls actually reacted this time

**Pull request merged**
